bot_settings:
  email: ""
  password: ""
  debug: False
  time_between_requests: 0.25
  time_between_runs: 5

locations:
  default:
    url: "https://www.pararius.com/huurwoningen"
    min_price: 800
    max_price: 1500
    min_area: 45
    message: ""
    applied_listings_location: "applied_listings"
  delft:
  den-haag:
  rotterdam:
  leiden:
  amsterdam:
    max_price: 1750

#twilio:
#  account_sid: ""
#  auth_token: ""
#  sender: ""
#  receivers:
#    User:
#      phone_number: ""
#      message: "Applied to {url} with price {price} in {location}"
#
#
